### ISSUE TITLE
Tensor out-of-bounds read

### ISSUE THREAD

**Issue by twuebi** [ROCm/pytorch#690] opened 2020-07-14 10:42 UTC
## 🐛 Bug

Indexing a GPU tensor with a list allows out of bounds reads.

## To Reproduce

```py
from torch import tensor
t = tensor([[    7,   135,  1449,     7,  5494, 14436,    38,    40,    70,    23,
             9,  1710,   392,     7,  2246,   346,  1468,    25,     7,   121,
             8, 26673,   655, 11142,    15,    52,     6,     2,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')

In [3]: t.shape                                                                                                                                               
Out[3]: torch.Size([1, 109])

t[[15]] # should fail with index out of bounds
Out[3]: 
tensor([[ 4674842241217339456,  4629806657795309632,     4644955860537376,
         -9218850774164963184,    36028867885924480,   -72057589759737856,
           -72057589759737856,   -72057589759737856,   -56843647366201344,
           -72057589759737856,    -9103775903119104,   -62484142016692224,
           -31881056909156573,   -32274956960712934,   -58136346607167159,
           -70368739899473920,   -39770044248586729,   -69242839992631296,
           -46830017000074981,   -41054651801403392,   -68048538422617786,
            -8235110176189952,   -72057572576365752,   -51642626639613650,
           -72057589759737336,   -72053144462912176,   -72057589759737856,
           -58779814325177824,   -64979960394208239,   -71776114783026937,
           -13832599313299449,   -62766716505030656,   -60961004864163543,
           -47554973134749696,   -39302915016697281,   -40779778189426688,
           -22302120197037497,   -40497203701088256,   -62654257065434552,
           -45580250251264000,   -70007842372132542,   -57135017947561984,
           -63220509848910798,   -70650214876184576,   -23981061570071791,
           -56521391669810884,   -66933728129235177,   -72057589759737855,
           -72057589759737856,   -11024433726834114,   -71471446975145398,
           -48922696876997844,   -45420451682798285,   -72057589759737855,
           -21990967001923581,   -72057589759737856,   -16641881589405951,
           -72057589759737855,   -21709496320312061,   -51464780645975512,
           -44572723922948304,   -53785540452881835,  4647856652431687808,
           578725763570794495,   578725746458757128,   865830274041120768,
           656694413791664389,  1735320741208658960,     1145730292781078,
           432626491604396629,      578351840625164,  2094184856236982276,
               15410376213006,   -72057589759737855,   -72057589759737856,
           -72057589759737856,   -72057589759737856,   -38640841510438612,
            -5154334432230129,   -64675318360819190,    -5154334432230911,
           -72057589759737856,    -5154334432230912,   -72057589759737856,
            -5154334432230912,   578993204616030805,   289365072285794308,
           288239206739214344,          34427109388,   -33437235244171264,
           -71465884988022704,   -33437235244171264,   -71465884988022704,
             4508135117087359,   288230402326667519,    77410222901962022,
                6606231706642,  6962829938312364160, -4575428314936594192,
         -8047809112583409664,    54096523459301472,   -72057589759737854,
           -72057589759737856,   -72057589759736552,   -71213164829605888,
           -72057589759736291,   -57133918435934208,   -72057589759737592,
           -31459209530834944]], device='cuda:0')

```

On my machine, the code below loops until 2404 before crashing with a memory access fault:

```py
for n in range(15000):
    print(n)
    print(t[[n]])
```

CPU correctly recognizes OOB:

```py
In [5]: t.cpu()[[24]]                                                                                                                                         
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-18df6e69e9c3> in <module>
----> 1 t.cpu()[[24]]

IndexError: index 24 is out of bounds for dimension 0 with size 1
```

## Environment

PyTorch version: 1.6.0a0+2a460c0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Linux Mint 19.1 Tessa
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
CMake version: version 3.17.2

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] numpydoc==0.9.2
[pip3] pytorch-lamb==1.0.0
[pip3] pytorch-lightning==0.8.0
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.6.0a0+2a460c0
[pip3] torchvision==0.6.0
[conda] Could not collect

## Additional context

GPU: Radeon VII
ROCm version: 3.5.1

**Comment by twuebi** [comment] 2020-07-14 10:53
This also happens on ROCm 2.10 with PyTorch 1.4.0:

```py
In [1]: import torch

In [2]: from torch import tensor
   ...: t = tensor([[    7,   135,  1449,     7,  5494, 14436,    38,    40,    70,    23,
   ...:              9,  1710,   392,     7,  2246,   346,  1468,    25,     7,   121,
   ...:              8, 26673,   655, 11142,    15,    52,     6,     2,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   ...:              0,     0,     0,     0,     0,     0,     0,     0,     0]],
   ...:        device='cuda:0')

In [3]: t[[14]]
Out[3]: 
tensor([[-4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746, -4702111234474983746, -4702111234474983746,
         -4702111234474983746]], device='cuda:0')

```

**Comment by twuebi** [comment] 2020-07-22 13:35
Not restricted to indexing with python lists, also happens when indexing with tensors:



```py
In [1]: import torch                                                                                                                                          

In [19]: a = torch.tensor([0]).cuda()                                                                                                                         

In [20]: a[torch.as_tensor([15])]                                                                                                                             
Out[20]: tensor([0], device='cuda:0')

In [21]: a[torch.as_tensor([1500])]                                                                                                                           
Out[21]: tensor([0], device='cuda:0')

In [22]: a[torch.as_tensor([1500000])]                                                                                                                        
Memory access fault by GPU node-1 (Agent handle: 0x563958d8dd70) on address 0x7f0f29771000. Reason: Page not present or supervisor privilege.
[1]    29213 abort (core dumped)  ipython

```

```py
In [2]: z = torch.zeros((10,10,300)).cuda()                                                                                                                   

In [3]: z.shape                                                                                                                                               
Out[3]: torch.Size([10, 10, 300])

In [4]: z[torch.as_tensor([15]), torch.as_tensor([15])].shape                                                                                                 
Out[4]: torch.Size([1, 300])

In [5]: z[torch.as_tensor([15]), torch.as_tensor([15])]                                                                                                       
Out[5]: 
tensor([[-3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -2.5754e+38,
                 nan, -7.3016e+29,  6.6967e+23,  7.0242e+20,  1.5825e-16,
          1.1073e+04, -6.0365e+07,  4.1773e-38,  6.0972e-28,  1.2969e-27,
          1.4724e-19,  6.7970e+31,  4.2389e-28,  0.0000e+00,  0.0000e+00,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -2.5654e+38, -2.5654e+38,         nan,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01,         nan,         nan,         nan,
         -2.6762e+38,         nan,         nan,         nan, -2.6762e+38,
                 nan,         nan,         nan, -2.6762e+38,         nan,
                 nan,         nan, -2.3837e+38, -2.3495e-38,  9.3718e-38,
          5.3267e-38, -1.7323e+10,  4.0195e+00,  1.8974e-19,  1.1824e-38,
          0.0000e+00, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,         nan,
                 nan,         nan, -2.5168e+38,         nan,         nan,
                 nan, -2.8791e+38,         nan,         nan,         nan,
         -2.5699e+38, -2.3552e+38, -2.4351e+38, -2.9415e+38,         nan,
         -2.5654e+38, -2.5654e+38,         nan,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00, -5.9221e-34,  1.0923e+03,
         -3.8599e-34,  7.8507e+02, -8.1853e-34,  9.5288e-44,  0.0000e+00,
          0.0000e+00, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -2.5754e+38, -2.5588e+38,  6.9931e-18,
          1.7366e-18,  3.1225e-39,  2.1955e-18,  6.9931e-18,  6.9391e-18,
          1.7347e-18,  1.7347e-18,  2.1973e-18,  2.1956e-18,  2.1973e-18,
          1.2197e-41,  0.0000e+00,  0.0000e+00, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -2.5654e+38,
         -2.5654e+38,         nan,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -2.5654e+38, -2.5654e+38,
                 nan,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,         nan,
         -2.8791e+38,         nan,         nan,         nan, -2.5699e+38,
                 nan,         nan, -2.9415e+38,         nan,         nan,
                 nan,         nan,         nan,         nan,         nan,
         -2.3495e-38,  1.7729e-15, -1.6438e-29,  3.9907e+33,  9.8930e-17,
         -1.1966e-30,  8.7425e+11,  3.4648e-40, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01, -3.7255e-01,
         -3.7255e-01, -2.9422e+38, -3.1312e+38,         nan,         nan,
         -2.9289e+38,         nan, -3.2338e+38,         nan, -2.9156e+38,
                 nan, -2.6647e+38,         nan, -2.9156e+38,         nan,
         -3.3463e+38,         nan, -2.5654e+38, -2.5654e+38,         nan,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],
       device='cuda:0')
```

**Comment by jithunnair-amd** [comment] 2020-07-22 14:09
We'll take a look into this. Do you happen to know if this same behaviour is observed in CUDA on NV GPUs?

**Comment by twuebi** [comment] 2020-07-22 14:27
Doesn't happen on NV GPUs.

**Comment by taylding-amd** [comment] 2024-12-05 21:57
I tested with the Radeon PRO W7700 and the latest PyTorch Docker image, and I can still reproduce the bug:
![image](https://github.com/user-attachments/assets/2a33b5b1-fd5f-45b1-97a9-37b665916896)

**Comment by naromero77amd** [comment] 2024-12-11 20:26
I cannot reproduce the issue on an MI200. I get the IndexError, which is what should happen:
```
from torch import tensor
t = tensor([[    7,   135,  1449,     7,  5494, 14436,    38,    40,    70,    23,
             9,  1710,   392,     7,  2246,   346,  1468,    25,     7,   121,
             8, 26673,   655, 11142,    15,    52,     6,     2,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0]],
       device='cuda:0')
print(t.shape)
# both of these should give indexing errors
t[15000]
t[110] 
```

@taylding-amd Can you please verify on your Radeon PRO W7700 that you are getting an IndexError and not a memory fault?

**Comment by naromero77amd** [comment] 2024-12-11 20:37
It is also working properly on navi3 (gfx1100).

@taylding-amd Unless the is a memory access fault on your end, the issue has been resolved in ROCm 6.2 or later and we can closed. I will wait to hear back from you, otherwise will close by end of week.

**Comment by taylding-amd** [comment] 2024-12-11 21:25
Thanks for checking it @naromero77amd, I don't get memory access fault with `t[110]` as well, the issue only happens when you access the tensor with `t[[]]`, can you try `t[[110]]`?
![image](https://github.com/user-attachments/assets/2480a1e1-9e71-4033-a25c-07663d65f590)

**Comment by naromero77amd** [comment] 2024-12-11 22:27
@taylding-amd Index error is the correct behavior :) 

It is a memory fault that would be incorrect behavior.

**Comment by naromero77amd** [comment] 2024-12-11 23:12
oops my fault, missed the double bracket. Yes, I am now able to reproduce the memory fault.

**Comment by naromero77amd** [comment] 2024-12-13 21:46
@twuebi I tested this out on NVIDIA V100 using the following docker image: `nvcr.io/nvidia/pytorch:24.10-py3`
```
>>> t[[15000]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 464, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 708, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 625, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 357, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 141, in __init__
    value_str = f"{value}"
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 993, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

>>> /opt/pytorch/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [0,0,0], thread: [96,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
...
```

This is actually a fatal assert. You can do a control-break back into the PyTorch terminal but you cannot do anything else on the NVIDIA GPU afterwards.

I would agree that it would be much nicer for the GPU to also throw an IndexError like the CPU. This limitation is there on the AMD and NVIDIA GPU. If you want this supported, my recommendation is that a separate github issue be filed in the github upstream repo as it is not specific to AMD.

**Comment by twuebi** [comment] 2024-12-13 21:55
I no longer use rocm, feel free to close the issue if you deem the current state fine

**Closed** 2024-12-13 21:56 UTC
Labels: Under Investigation
